# pico tool viewer — presents a static image once at boot.
# Generated by pico tool; rendered for the configured display backend.
import time

BLACK_BIN = "{{BLACK_BIN}}"
RED_BIN = "{{RED_BIN}}"
YELLOW_BIN = "{{YELLOW_BIN}}"
OVERRIDES = {{OVERRIDES_JSON}}


def _read_bin(path, length):
    if not path:
        return bytes(length)
    try:
        with open(path, "rb") as f:
            data = f.read()
        if len(data) < length:
            data = data + bytes(length - len(data))
        return data[:length]
    except Exception:
        return bytes(length)


def main():
    from {{BACKEND_MODULE}} import Backend

    backend = Backend(overrides=OVERRIDES)
    backend.init()
    buf_len = backend.ui_bw * backend.ui_h

    black = _read_bin(BLACK_BIN, buf_len)
    red = _read_bin(RED_BIN, buf_len)
    yellow = _read_bin(YELLOW_BIN, buf_len) if YELLOW_BIN else None

    backend.set_led(1)
    try:
        if yellow is not None:
            try:
                backend.present(black, red, yellow)
            except TypeError:
                backend.present(black, red)
        else:
            backend.present(black, red)
    finally:
        backend.set_led(0)

    # Image stays on the e-paper without power; idle quietly.
    while True:
        time.sleep_ms(60000)


main()
